#! /bin/sh


sxhkd &
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# makes firefox show up in the right desktop
bspc config ignore_ewmh_focus true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xset +fp /home/vicber/.fonts
xset fp rehash

# background
feh --bg-fil "$HOME/.config/backgrounds/4k-tree-alone-dark-evening-wallpaper.jpg"

# for intellij
wmname LG3D

# caps lock -> escape
setxkbmap -option caps:escape

# 16 is the trackpad
xinput --set-prop 16 'libinput Accel Speed' 0.28
xinput --set-prop 16 "libinput Natural Scrolling Enabled" 1

$HOME/.config/polybar/launch.sh &
